version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - /var/lib/docker/volumes/simple-currency-converter-api_mongodb_data/_data:/data/db
    command: mongod --dbpath /data/db

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
